// <auto-generated />
namespace PruebaFalabella.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_passw_to_users : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_passw_to_users));
        
        string IMigrationMetadata.Id
        {
            get { return "201901202218570_Added_passw_to_users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
